#!/usr/bin/env bash
# Shared settings for the 2-node vLLM deployment.

ROOT="${ROOT:-$HOME/llm_serving}"
IMAGE="${IMAGE:-$ROOT/build/vllm-gloo-nccl-patched.sandbox}"

MODEL="${MODEL:-Qwen/Qwen2.5-32B-Instruct}"
SERVED_MODEL="${SERVED_MODEL:-qwen2.5-32b}"

CONTROL_IF="${CONTROL_IF:-ens11f0}"

# Firewall layout
RAY_GCS_PORT="${RAY_GCS_PORT:-50000}"
RAY_NODE_MANAGER_PORT="${RAY_NODE_MANAGER_PORT:-50001}"
RAY_OBJECT_MANAGER_PORT="${RAY_OBJECT_MANAGER_PORT:-50002}"
RAY_RUNTIME_ENV_PORT="${RAY_RUNTIME_ENV_PORT:-50003}"
RAY_DASHBOARD_AGENT_GRPC_PORT="${RAY_DASHBOARD_AGENT_GRPC_PORT:-50004}"
RAY_DASHBOARD_AGENT_HTTP_PORT="${RAY_DASHBOARD_AGENT_HTTP_PORT:-50005}"
RAY_METRICS_PORT="${RAY_METRICS_PORT:-50006}"
RAY_CLIENT_PORT="${RAY_CLIENT_PORT:-50007}"
RAY_DASHBOARD_PORT="${RAY_DASHBOARD_PORT:-50008}"
RAY_WORKER_MIN_PORT="${RAY_WORKER_MIN_PORT:-50020}"
RAY_WORKER_MAX_PORT="${RAY_WORKER_MAX_PORT:-50179}"

# vLLM internal ports. This is NOT the HTTP API port.
VLLM_INTERNAL_PORT="${VLLM_INTERNAL_PORT:-50300}"
VLLM_NCCL_SO_PATH="${VLLM_NCCL_SO_PATH:-$ROOT/build/torch-gloo-port/pytorch/build/nccl/lib/libnccl.so.2.21.5}"
# HTTP API port; kept inside the admin-opened range.
API_PORT="${API_PORT:-50380}"

# Patched Gloo / NCCL listener ranges
GLOO_PORT_MIN="${GLOO_PORT_MIN:-50400}"
GLOO_PORT_MAX="${GLOO_PORT_MAX:-50599}"
NCCL_PORT_MIN="${NCCL_PORT_MIN:-50600}"
NCCL_PORT_MAX="${NCCL_PORT_MAX:-51000}"

TP="${TP:-4}"
PP="${PP:-2}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-4096}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-16}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.90}"

container_env_args() {
  local node_ip="$1"
  printf '%s\n' \
    --env "VLLM_HOST_IP=$node_ip" \
    --env "VLLM_PORT=$VLLM_INTERNAL_PORT" \
    --env "VLLM_USE_V1=0" \
    --env "VLLM_ATTENTION_BACKEND=XFORMERS" \
    --env "GLOO_SOCKET_IFNAME=$CONTROL_IF" \
    --env "GLOO_PORT_MIN=$GLOO_PORT_MIN" \
    --env "GLOO_PORT_MAX=$GLOO_PORT_MAX" \
    --env "NCCL_NET=Socket" \
    --env "NCCL_IB_DISABLE=1" \
    --env "NCCL_SOCKET_IFNAME==$CONTROL_IF" \
    --env "NCCL_SOCKET_FAMILY=AF_INET" \
    --env "NCCL_PORT_MIN=$NCCL_PORT_MIN" \
    --env "NCCL_PORT_MAX=$NCCL_PORT_MAX" \
    --env "VLLM_NCCL_SO_PATH=$VLLM_NCCL_SO_PATH" \
    --env "NCCL_DEBUG=INFO" \
    --env "NCCL_DEBUG_SUBSYS=INIT,NET,ENV" \
    --env "PYTHONUNBUFFERED=1"
}
